package com.despegar.integration.mongo.support;

import com.fasterxml.jackson.databind.PropertyNamingStrategy.PropertyNamingStrategyBase;

/**
 * Maps the standard "id" field to the autogenerated mongo id called "_id"
 * 
 * @author jformoso
 */
class IdWithUnderscoreStrategy
    extends PropertyNamingStrategyBase {

    @Override
    public String translate(final String propertyName) {
        if (propertyName == null) {
            return propertyName; // garbage in, garbage out
        }

        if (propertyName.equals("id")) {
            return "_id";
        } else {
            return propertyName;
        }
    }

}
